# Usa a imagem oficial do Nginx como base
FROM nginx:alpine

# Copia o arquivo index.html para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html/index.html

# Expõe a porta padrão do Nginx
EXPOSE 80
